### ISSUE TITLE
Wont Run, pygame.base.pyd not found

### ISSUE THREAD

**Issue by nsd4fr** [KobayashiKojiLKQ/Mouse-Tracker#1]
Upon downloading and unzipping, I cannot get the program to run. 

Here is the log issue

Traceback (most recent call last):
  File "MT(0.1.5.0).py", line 2, in module
  File "C:\Python34\lib\site-packages\pygame\__init__.py", line 136, in module
  File "loader", line 10, in module
  File "loader", line 8, in __load
ImportError: (DLL load failed: The specified module could not be found.) 'C:\\Users\\local\\Downloads\\Mouse Tracker v0.1.0.0\\pygame.base.pyd'

**Comment by Sbrown-WilliamsCrusher** [comment]
Traceback (most recent call last):
  File "MT(0.1.5.0).py", line 2, in <module>
  File "C:\Python34\lib\site-packages\pygame\__init__.py", line 136, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: The specified module could not be found.) 'C:\...\\Mouse-Tracker-0.1.0.0\\Mouse-Tracker-0.1.0.0\\Mouse Tracker v0.1.0.0\\Mouse Tracker v0.1.0.0\\pygame.base.pyd'

**Comment by bjparker1226** [comment]
Hey!  I currently have not found a fix for this issue.  Part of the problem is that I can't actually recreate the issue. I've only seen it once before in an earlier build, and even then, the error only showed up on one particular PC. My laptop, and the computers of several others are able to run it fine, so solving it without being able to recreate it might be a bit difficult. I do have some other people looking into it with me though, who are not knowledgeable than I am in Python, and ESPECIALLY in PyGame, the module I suspect is causing the issue.

**Comment by bjparker1226** [comment]
I will, hopefully sometime later today, upload an older build that should hopefully function, but won't have ALL the features of the current build. That is, of course, until we find the actual long-term solution to the issue at hand.
